version = 0.1
[default.deploy.parameters]
stack_name = "landingzone-organization"
resolve_s3 = true
s3_prefix = "landingzone-organization"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
